site_name: terraform-provider-kcps
site_url: https://ezoiwana.github.io/terraform-provider-sakuracloud
site_description: terraform-provider-kcps
site_author: '@ezoiwana'
copyright: Copyright (C) 2018 ezoiwana
theme: readthedocs
extra_css:
  - css/custom.css
pages:
  - Home: index.md
  - Install: installation.md
  - Configuration:
    - Provider: configuration/provider.md
    - Resources:
      - Value VM: configuration/resources/value_vm.md
      - Volume: configuration/resources/volume.md
      - Template: configuration/resources/template.md
      - Snapshot: configuration/resources/snapshot.md
      - VMSnapshot: configuration/resources/vmsnapshot.md
      - Snapshot Policy: configuration/resources/snapshot_policy.md
      - Nic: configuration/resources/nic.md
      - Public IP: configuration/resources/publicip.md
      - Firewall: configuration/resources/firewall.md
      - NAT/PortForward: configuration/resources/nat_portforward.md
      - LoadBalancer: configuration/resources/loadbalancer.md
    - Data Sources:
      - Value VM: configuration/data_sources/value_vm.md
      - Volume: configuration/data_sources/volume.md
      - Guest OS: configuration/data_sources/guestos.md
      - Template: configuration/data_sources/template.md
      - Snapshot: configuration/data_sources/snapshot.md
      - VMSnapshot: configuration/data_sources/vmsnapshot.md
      - Snapshot Policy: configuration/data_sources/snapshot_policy.md
      - Nic: configuration/data_sources/nic.md
      - Public IP: configuration/data_sources/publicip.md
      - Network: configuration/data_sources/network.md
      - ServiceOffering: configuration/data_sources/serviceoffering.md
      - DiskOffering: configuration/data_sources/diskoffering.md
      - Zone: configuration/data_sources/zone.md
      - Firewall: configuration/data_sources/firewall.md
      - NAT/PortForward: configuration/data_sources/nat_portforward.md
      - LoadBalancer: configuration/data_sources/loadbalancer.md

